### PR TITLE
Remove pysha3 dependency.

### PR DESCRIPTION
**Pull request by orhtej2**
## Problem

- `bookworm` build fails.

## Solution

- Remove transitive `pysha3` dependency.

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by orhtej2** [comment]
!bookwormtestme

**Comment by orhtej2** [comment]
!testme !bookwormtestme

**Comment by orhtej2** [comment]
!testme

**Comment by orhtej2** [comment]
!testme

**Comment by orhtej2** [comment]
!bookwormtestme

**Comment by orhtej2** [comment]
!bookwormtestme

**Comment by Salamandar** [comment]
I rebased your branch on the manifestv2 port.

**Comment by Salamandar** [comment]
!testme

**Comment by Thovi98** [comment]
!testme

**Comment by Salamandar** [comment]
Greenlet is missing `May 02 20:16:59 domain.tld python3[8352]: ERROR:root:Unhandled exception: No module named 'greenlet'
`

**Comment by orhtej2** [comment]
> Greenlet is missing `May 02 20:16:59 domain.tld python3[8352]: ERROR:root:Unhandled exception: No module named 'greenlet' `

its

**Comment by Salamandar** [comment]
I rebased the testing branch, could you rebase your own branch ? :)

**Comment by orhtej2** [comment]
> I rebased the testing branch, could you rebase your own branch ? :)

I can, but I feel it's the same story as https://github.com/YunoHost-Apps/mygpo_ynh/pull/26 where bumping random dependencies is fragile and not a good solution in the long run

**Comment by orhtej2** [comment]
Upstream had last commit 3 years ago, can we just move the app to graveyard and move on?

**Comment by Salamandar** [comment]
hahaha
Yeah, agreed. TBH I wanted to move it at least to packagingv2 just to "wrap it" but yeah, maybe supporting bookworm is out of scope now.

**Pull request closed without merging**
