### PR TITLE
Apply example_ynh

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *Level0*

## Solution
- *Apply example_ynh*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!test

**Comment by yalh76** [comment]
!testme

**Comment by anmol26s** [comment]
@yalh76 
I want to push https://github.com/YunoHost-Apps/zeronet_ynh/pull/22 to this PR. This will solve the dependencies problem.
This should be done ASAP. Zeronet is breaking Yunohost.

**Comment by yalh76** [comment]
> @yalh76 
> 
> I want to push https://github.com/YunoHost-Apps/zeronet_ynh/pull/22 to this PR. This will solve the dependencies problem.
> 
> This should be done ASAP. Zeronet is breaking Yunohost.

Not sure #22 will solve dependency problem. Look at now testing if it's ok.

**Pull request merged**
